// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZR-NPrlbFQG5O8lJ-hakr_XrNFh3kEXM',
    appId: '1:422819215261:web:a5054757bc6fb1938ba174',
    messagingSenderId: '422819215261',
    projectId: 'firebaseinclass',
    authDomain: 'fir-inclass-ed536.firebaseapp.com',
    storageBucket: 'firebaseinclass.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQHdoXjJ6uzX_DTRSdG7ohOi0QSvHjfqc',
    appId: '1:422819215261:android:c89884a268dee6a68ba174',
    messagingSenderId: '422819215261',
    projectId: 'firebaseinclass',
    storageBucket: 'firebaseinclass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptKcOBIZ1xw6Gm2FWMwKvD3pMfdz-8MQ',
    appId: '1:422819215261:ios:008ce3d4d47fb4178ba174',
    messagingSenderId: '422819215261',
    projectId: 'firebaseinclass',
    storageBucket: 'firebaseinclass.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCptKcOBIZ1xw6Gm2FWMwKvD3pMfdz-8MQ',
    appId: '1:422819215261:ios:008ce3d4d47fb4178ba174',
    messagingSenderId: '422819215261',
    projectId: 'firebaseinclass',
    storageBucket: 'firebaseinclass.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZR-NPrlbFQG5O8lJ-hakr_XrNFh3kEXM',
    appId: '1:422819215261:web:e27997bb674aa8068ba174',
    messagingSenderId: '422819215261',
    projectId: 'firebaseinclass',
    authDomain: 'fir-inclass-ed536.firebaseapp.com',
    storageBucket: 'firebaseinclass.firebasestorage.app',
  );
}
